add_rules("mode.debug", "mode.release")
set_languages("c99", "c++17")
add_requires("glfw", "zlib", "opencl", "glad")

target("ReSTIR")
    set_kind("binary")
    add_packages("glfw", "zlib", "opencl", "glad")
    add_files("template.cpp")
    add_files("cornellboxscene.cpp")
    add_files("letterscene.cpp")
    add_files("light_manager.cpp")
    add_files("mountainscene.cpp")
    add_files("mygamescene.cpp")
    add_files("scatterscene.cpp")
    add_files("world_to_obj.cpp")
    add_files("mygame.cpp")
    add_files("world.cpp")
